### ISSUE TITLE
Manually hiding and showing DrawerPanel in CoreScaffold using dart fails with no error

### ISSUE THREAD

**Issue by janvladimirmostert** [dart-lang/polymer-dart#12]
CoreScaffold e = shadowRoot.querySelector('core-scaffold');
e.closeDrawer();

Drawer doesn't close as per documentation neither does togglePanel work.

I have posted a StackOverflow question here with plenty of details:
https://stackoverflow.com/questions/27957771/manually-hiding-and-showing-drawer-panel-in-core-scaffold-using-dart

If more details are required, I'm happy to update on both sites.

**Comment by jakemac53** [comment]
It looks like togglePanel() only has an effect when in responsive mode (just make your browser really skinny). For instance go to the js demo here https://www.polymer-project.org/components/core-drawer-panel/demo.html and try typing into the console `document.querySelector('core-drawer-panel').togglePanel();`. Nothing will happen if your browser window is large.

One thing you can do is force it always into the responsive layout by running `document.querySelector('core-drawer-panel').forceNarrow = true;`. Then calling togglePanel will work.

If you think this is the wrong behavior please file a bug here https://github.com/Polymer/core-drawer-panel

**Comment by jakemac53** [comment]
looks like this was already filed https://github.com/Polymer/core-drawer-panel/issues/43

**Comment by janvladimirmostert** [comment]
shadowRoot.querySelector('core-drawer-panel').forceNarrow = true; 
throws a stacktrace and so does: 
CoreScaffold e = shadowRoot.querySelector('core-scaffold');
e.shadowRoot.querySelector('core-drawer-panel').forceNarrow = true;

Exception: Uncaught Error: Class 'CoreDrawerPanel' has no instance setter 'forceNarrow='.
NoSuchMethodError: method not found: 'forceNarrow='

How do I set forceNarrow in dartCode and how would I set it in the HTML?

Should I log an enhancement request to document this feature ?

**Comment by jakemac53** [comment]
can you make sure you are on the most recent version of core-elements? forceNarrow should exist https://github.com/dart-lang/core-elements/blob/master/lib/core_drawer_panel.dart#L109

**Comment by jakemac53** [comment]
As far as setting in in the html, it would need to be exposed on core-scaffold and then passed down to core-drawer-panel. You could submit a feature request at that repo https://github.com/polymer/core-scaffold

**Comment by janvladimirmostert** [comment]
pub cache repair says I'm on core_elements 0.4.0+6... from which I can see that I'm about 2 months behind based on https://pub.dartlang.org/packages/core_elements

This is my pubspec.yaml, I've increased the version numbers for polymer and paper_elements, did a rm -rf .pub and pub cache repair, but it still says core_elements 0.4.0+6

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: any
  browser: any
  polymer: '>=0.15.0 <0.17.0'
  paper_elements: '>=0.5.0 <0.7.0'
  less_dart: ">=0.1.3 <0.2.0"
  event_bus: ">=0.3.0+2 <0.4.0"
transformers:
- less_dart:
    entry_point: web/alm.less
    build_mode: dart
- polymer:
    entry_points: web/index.html
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]

**Comment by jakemac53** [comment]
did you try running `pub upgrade`? `pub get` will not actually upgrade any
packages which have already been downloaded.
