### ISSUE TITLE
Request: SPA tutorial for Polymer-dart

### ISSUE THREAD

**Issue by thetechnaddict** [dart-lang/polymer-dart#16]
It would be great to have the Polymer-dart version of this tutorial/article:

https://www.polymer-project.org/articles/spa.html

**Comment by kwalrath** [comment]
Corresponding dartlang.org bug: https://github.com/dart-lang/www.dartlang.org/issues/1243

**Comment by jakemac53** [comment]
This exists now, have fun! https://www.dartlang.org/polymer/spa/
