### ISSUE TITLE
Investigate optimizing <link rel="stylesheet"> tags in the same way as <core-style>

### ISSUE THREAD

**Issue by felixc** [dart-lang/polymer-dart#20]
Currently, custom elements that share stylistic attributes are recommended to use `<core-style>` to avoid duplication of code (in the case of writing or inlining the CSS multiple times) or extra network requests (in the case of linking to the same stylesheet from multiple places).

This is a good optimization, but it represents an extra step in the learning curve, since it's a Polymer-specific API. It's also somewhat non-idiomatic compared to regular HTML+CSS.

It would be great if the existing standard `<link rel="stylesheet">` mechanism could be optimized in the same way as `<core-style>`, or alternatively, transformed into `<core-style>` references.

**Comment by felixc** [comment]
I don't think this should be assumed stale, as I think the feature request is still valid. Though perhaps it's just not going to happen?

**Comment by jakemac53** [comment]
I marked it as stale since the new polymer has a [different mechanism](https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules), but I agree that `not planned` is probably a better description since its still a polymer specific api.
