### ISSUE TITLE
update all uses of ObservableTransform

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/polymer-dart#23]
we missed this line in the change to use named arguments:

https://github.com/dart-lang/polymer-dart/blob/master/lib/src/build/common.dart#L230

I'll create a fix shortly and release it as 0.15.3+4

**Comment by sigmundch** [comment]
Fix submitted in c8fc3d9b60a09f95b76ec92fd0053a50a5614daa

**Comment by sigmundch** [comment]
and published

**Comment by vdakalov** [comment]
Thank you very much. You helped me a lot!
