### ISSUE TITLE
Pub get: The null object does not have a getter 'isNotEmpty'

### ISSUE THREAD

**Issue by eee-c** [dart-lang/polymer-dart#28]
I cannot `pub get` or `pub upgrade` with 0.16 on Dart 1.8.5. With a basic `pubspec.yaml`:

```yaml
name: svg_example
dependencies:
  polymer: any
dev_dependencies:
  unittest: any
```

A pub get on a new project (or pub upgrade on an old project) results in:

```
pub get
Resolving dependencies... (1.8s)
The null object does not have a getter 'isNotEmpty'.

NoSuchMethodError: method not found: 'isNotEmpty'
Receiver: null
Arguments: []
dart:core                                                                                                                                Object.noSuchMethod
package:path/src/style/posix.dart 34                                                                                                     PosixStyle.rootLength
package:path/src/internal_style.dart 46                                                                                                  InternalStyle.getRoot
package:path/src/parsed_path.dart 47                                                                                                     ParsedPath.ParsedPath.parse
package:path/src/context.dart 529                                                                                                        Context._parse
package:path/src/context.dart 108                                                                                                        Context.dirname
package:path/path.dart 145                                                                                                               dirname
...
```

Adding a constraint on Polymer to be less than `0.16` resolves the problem. 

Does 0.16 need an SDK constraint?

**Comment by andreasolund** [comment]
Yes, it seems like it should! When you run [polymer-spa-example](https://github.com/dart-lang/polymer-spa-example.git) with the `1.8.5` SDK, `pub` outputs:
 `Package web_components requires SDK version >=1.9.0-dev.7.1 <2.0.0 but the current SDK is 1.8.5.`

**Comment by jakemac53** [comment]
Yes, it does require >=1.9.0-dev.7.1. There was a bug in pub with path based dev dependencies which the `initialize` package uses for one of its tests.

**Comment by andreasolund** [comment]
@jakemac53 just to clarify my comment. Shouldn't [pubspec.yaml#L85](https://github.com/dart-lang/polymer-dart/blob/master/pubspec.yaml#L85) also be changed to `sdk: '>=1.9.0-dev.7.1 <2.0.0'` to reflect the same environment dependency as with `web_components` that `polymer-dart` depends on? Is there a reason not to restrict the environment dependency tighter?

**Comment by jakemac53** [comment]
yes, it should have that sdk constraint
