### ISSUE TITLE
Remove requirement to call superclass life-cycle methods

### ISSUE THREAD

**Issue by almstrand** [dart-lang/polymer-dart#31]
To avoid common programming mistakes, can the requirement to call the superclass life-cycle methods be removed when writing custom elements? This appears to not be a requirement in the JavaScript version, and forgetting to call `super.attached` and `super.detached` in polymer.dart can have problematic side-effects.

The [relevant page](https://www.dartlang.org/docs/tutorials/polymer-intro/#life-cycle-methods) on the dartlang.org website states that "The constructor or overriding method must call the superclass constructor or method first."

The implication is that these life-cycle methods must be implemented as such:

```
ready() {
  super.ready();
  ...
}

domReady() {
  super.domReady();
  ...
}

attached() {
  super.attached();
  ...
}

detached() {
  super.detached();
  ...
}

```

However, looking at the [polymer.dart implementation](https://github.com/dart-lang/polymer-dart/blob/784eb911c8b71e9a56791acfaf8ca088ba941fcb/lib/src/instance.dart), only the `attached` and `detached` methods have implementations in the base class. So, calling `super.ready()` and `super.domReady()` currently has no effect.

Developers may inadvertently omit calling the superclass implementation. Per the above, that would cause no problem in case of `ready` or `domReady` but can cause side-effects that are difficult to track down in case of, e.g., `attached`. As an example, if one fails to call `super.attached()` any subsequent call to `hasBeenAttached` will return `false` regardless of whether the element was attached. There will be no warning to the developer by any linter, dart2js, etc.

Since the dartlang.org website implies that these superclass methods must *always* be called, and since there can be negative side-effects from forgetting to call the methods, can the polymer.dart implementation be changed such that the relevant code in the superclass is always executed similar to how it is done in the [JavaScript implementation](https://github.com/dart-lang/polymer-dart/blob/fa2fbb5fd00bcfe0dbf656a3a2ccf72f15c3708d/lib/src/js/polymer/polymer.js) shown below?

```
/**
 * Low-level lifecycle method called as part of standard Custom Elements
 * operation. Polymer implements this method to provide basic default 
 * functionality. For custom create-time tasks, implement `attached` 
 * instead, which is called immediately after `attachedCallback`.   * 
 * @method attachedCallback
 */
attachedCallback: function() {
  // when the element is attached, prevent it from unbinding.
  this.cancelUnbindAll();
  // invoke user action
  if (this.attached) {
    this.attached();
  }
  if (!this.hasBeenAttached) {
    this.hasBeenAttached = true;
    if (this.domReady) {
      this.async('domReady');
    }
  }
},
```

In the JavaScript implementation, it seems `attached` can be implemented without needing to call any prototype function. The above problem with `hasBeenAttached` remaining false would not occur as `_hasBeenAttached` is always assigned `true` after the custom element's `attached` method has been called.

**Comment by zoechi** [comment]
Changing this also limits its usefulness. 
In attached I can decide whether my custom code should be executed just before or after the default `attached()` implementation by putting code before or after the `super.attached()` call. 

One reason why JavaScript doesn't need this is because JavaScript has no classes and therefore doesn't allow to override class methods.
If you override `attached()` and don't add the call to the base implementation you override the method with an empty implementation thus hide the default implementation.
This is normal behavior in object oriented languages.

For other methods like `ready()` where it doesn't matter if `super.ready()` is called or not is because the default implementation is a method which does nothing.

**Comment by almstrand** [comment]
What would be an example of a scenario where `super.attached()` or `super.detached()` needs to be called after the subclass implementation?

Generally yes - flexibility is a good thing but there appears to be no benefit here. On the contrary, promoting encapsulation and hiding the underlying complexities of these life-cycle methods is critical considering the consequences of failing to call the default implementation.

Additional benefits of the proposed change are increased compatibility with polymer.js (if the suggested flexibility was of benefit, the JavaScript version would/could offer it as well), removal of ambiguity as to when the default implementation should be called, and thereby lowering the barrier of adoption by new developers.

Yes the default implementation of `ready()` and `domReady()` already does not need to be called from the subclass, as it does nothing. So removing the requirement to call the super class implementation has a net-0 effect.

The only case that comes to min in favor of keeping the current implementation is to enable calling `cancelUnbindAll()` in the subclass' `detached()` implementation. However, the same effect can be had by setting `preventDispose = true` so consequentially the proposed change would have the additional benefit of removing redundancy and promoting a single way to achieve this.
