### ISSUE TITLE
Attributes on * were data bound prior to Polymer upgrading the element

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#38]
See https://github.com/dart-lang/polymer-dart/issues/33

**Comment by jakemac53** [comment]
@markhats are  you able to post a repro? Most likely this is due to elements being registered out of order. If you open up your web inspector and look at the *.web_components.bootstrap.dart file you can see the order in which elements are being registered (look for CustomElementProxy and CustomTag).

**Comment by markhats** [comment]
OK -  I think I've got a reasonable repro now. I couldn't seem to reproduce it on a small app so I stripped my app back to somewhere near the minimum required for the issue to show:

[Test Repro](http://www.autograph-maths.com/Autograph-New-Polymer.zip)

If you run the app, you will see the following error generated:
```Attributes on slider-control were data bound prior to Polymer upgrading the element. This may result in incorrect binding types. (:1)```

This becomes a problem once there are some bindings in place. Uncommenting the 'slider.dart' import in components/popover/panes/line2dpane.dart seems to get rid of the error for some reason but, as far as I can see, there is no reason to need that import. I guess this fix may be similar to the workaround you mentioned previously, whereby all components are imported on the Dart side.

**Comment by jakemac53** [comment]
great, I will take a look.

**Comment by jakemac53** [comment]
Ok, so this is being caused by a cyclical dependency. The file `popoverobjectpane.dart` imports `../../autograph.dart`, which then imports `popoverobjectpane.dart` via the import to `components/popover/panes/line2dpane.dart`. When there are these cyclical dependencies then it is not possible for polymer to know in what order it should register things, and in your case it chooses wrong. There is a warning in the logs about this:

    [Warning from polymer (PolymerBootstrapTransformer) on Autograph|web/autograph.html]:
    We have detected a cycle in your import graph when running initializers on Line2DPane. This
    means the super class PopoverObjectPane has a dependency on this library (possibly
    transitive).asset:Autograph/web/components/controls/slider.dart

This warning isn't properly making its way to the warning dialog on the front page though, so I will look into that.

In general, this is caused by the use of parts in autograph.dart. I would just switch it to use imports/exports and then directly include the AxesObject and AxesObjectDrawable classes from their original dart files (in popoverobjectpane.dart).

With polymer in general, its a good idea to avoid the use of parts. Things behave most consistently if every single polymer element has its own library.

**Comment by markhats** [comment]
OK - thanks.

So should every file/class (even non-polymer elements) ideally be a separate library then, if it can possibly be imported by a polymer element?

**Comment by jakemac53** [comment]
It is really just files which contain @CustomTag annotations on classes. By each of these living in its own library it makes it a lot easier to avoid cyclical dependencies.

**Comment by jakemac53** [comment]
marking as closed for now, but feel free to re-open if needed

**Comment by jakemac53** [comment]
Also its worth noting that using show/hide does not help this situation. Polymer has to read all CustomTag annotations on all classes of any library you import, regardless of if they are visible or not by your actual file. You might only care about class A, but polymer doesn't know whether or not A actually depends on B in the same library, so it has to assume it does.

**Comment by markhats** [comment]
In my case, the AxesObject and AxesObjectDrawable classes that are causing the problem do not have the @CustomTag annotation as they are not polymer elements. They are really just 'model' classes contained in the 'autograph' library. However, since the 'autograph' library also uses the line2dpane custom element that imports these classes, I am getting the cyclical dependency. 

I guess I did sort of think that using show would prevent any cyclic situations. However, as you say, it doesn't. I think the only solution will be to take my model classes out of the 'autograph' library and put them into a separate library or libraries.

I wonder why this wasn't an issue pre-polymer 0.16.0?

**Comment by jakemac53** [comment]
Kind of a long story, but basically the way your application is crawled now is completely different. Before we found @CustomTag annotations by looking at script tags found in your html imports, and we would only look in the top level library there (which had its own issues). Now we crawl all your dart imports as well (since you no longer have to have manual html imports).

**Comment by jakemac53** [comment]
And yes, you could still use parts for all your files which don't contain @CustomElement annotations.

**Comment by markhats** [comment]
Not though if they are model class files imported by polymer elements, such AxesObject and AxesObjectDrawable. These don't have @CustomTag annotations but still can't be 'part of' files it seems.

**Comment by jakemac53** [comment]
The reason in your particular case is that the library which they are a part of is importing some custom elements (which are then importing the original library). Basically, you could separate that out so there is a library which only has imports/parts which are not custom elements. Then you can export that library from your main library to expose it as part of your main api, and import it in your custom element dart files so they have access to the shared models/etc.

**Comment by jakemac53** [comment]
To clarify, heres a really quick example of a possible file layout you could use, https://gist.github.com/jakemac53/85b53ae30e3e766dd3d2

**Comment by markhats** [comment]
Thanks - that's super helpful!
