### ISSUE TITLE
Polymer 0.16.0 doesn't warn anymore about missing entry_points

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#39]
0.15.0 warned about uninitialized elements but 0.16.0 loads the page, the Polymer elements don't show and no error/warning/hint is shown.

**Comment by jakemac53** [comment]
I am a bit confused, sounds like two different things?

**Comment by zoechi** [comment]
I played a bit around with an example from a StackOverflow question and because it didn't work I switched back to Polymer 0.15.5 where I figured the transformer config misses an entry for the index.html (because of the error message). 
Then I removed the entry_point from the transformer config again and switched back to 0.16.0+4 where I didn't get the error message.
After adding the entry_point again it worked in 0.16.0+4 as well.
Hope this makes it more clear.
