### ISSUE TITLE
Use new test library instead of unittest.

### ISSUE THREAD

**Issue by damondouglas** [dart-lang/polymer-dart#514]
Would it be acceptable to submit a pull request replacing the `unittest` library with [test](https://pub.dartlang.org/packages/test)?

**Comment by jakemac53** [comment]
Unfortunately our test bots don't yet support unittest afaik, so we can't really switch without also changing our entire tooling story :(.

**Comment by jakemac53** [comment]
This dependency shouldn't leak though, as its only a dev dependency. You are free to use `test` in your own polymer apps.
