### ISSUE TITLE
Polymer doesn't recognize inline svg in the HTML file (in pub build) 

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/polymer-dart#515]
A new issue to reopen original one (Polymer doesn't recognize inline svg in the HTML file (in pub build) #172).

I think this issue is not closed. I've just made (dart 10.0.1 + polymer 16.3+3) a polymer component with an svg inside and I have warnings:

    <polymer-element name="svg-element-editor">
        <template>
        <style>

            :host {
                position: relative;
            }

            /**
                           Gradient definitions need to be registered
                           on dart side (can't figure out why for now, just live with it)
                       **/

            .node_red {
                stroke: black;
                fill: url("#gradred")
            }

            .node_green {
                stroke: black;
                fill: url("#gradgreen")
            }
        </style>
        <div layout horizontal fit>
            <svg flex id="myStage">
                
            </svg>
        </div>
     </template>
    </polymer-element>

**Comment by jakemac53** [comment]
Basic svg things seem to work fine now
