### ISSUE TITLE
Update/add documentation

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#523]
The readme and other documentation need to be updated.

- [x] Update the readme
- [x] Update dartlang.org

**Comment by jakemac53** [comment]
@Sfshaza @kwalrath please link any dartlang.org related issues here as they get created

**Comment by kwalrath** [comment]
OK, will do.

**Comment by rbishop-bah** [comment]
Will there be any sort of migration guide so that we have a cheat sheet for what changes we need to make to get to Polymer 1.0?

**Comment by jakemac53** [comment]
We will have something yes, not sure exactly what it will look like at this time though.

**Comment by jakemac53** [comment]
calling this done for now, wiki is updated and readme is updated, dartlang pages mostly redirect to the wiki now
