### ISSUE TITLE
Update polymer SPA example

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#524]
The [polymer spa example](https://github.com/dart-lang/polymer-spa-example) needs to get updated with the new version.

**Comment by Sfshaza** [comment]
Yes! I'd like to have the before/after fino.

**Comment by jakemac53** [comment]
It appears the same tutorial was never ported to 1.0, and it would require a pretty extensive overhaul. Looking into other options, possibly a dart port of https://github.com/PolymerElements/polymer-starter-kit

**Comment by jakemac53** [comment]
I think the starter kit is the right approach here, and it could be added to stagehand as a template (polymer-full?)

**Comment by jakemac53** [comment]
@montyr75 has ported the starter kit https://github.com/montyr75/polymer_dart_starter_kit/
