### ISSUE TITLE
Investigate memory leak

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#528]
Pretty sure we are leaking memory today, although I haven't checked super recently. This is expected in dartium but not dart2js. This could be coming from polymer js itself, so the best first step is probably to build a quick test to see if it can be duplicated there, and if so then file a bug on that repo.

**Comment by donny-dont** [comment]
Do you have any more info on it? I remember finding a huge memory leak in non-chrome browsers, https://github.com/Polymer/ShadowDOM/pull/512. I had a potentially automated test for that particular issue I passed onto the Polymer team.

**Comment by jakemac53** [comment]
I haven't had any time to investigate it yet - I think it happens regardless of the polyfills though.

**Comment by jakemac53** [comment]
looks like we are fine actually
