### ISSUE TITLE
serialize/deserialize unavailable in PolymerElement

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/polymer-dart#530]
In 1.0 and back to 0.5 you could use serialize/deserialize to handle custom types. This is present in Polymer 1.0, http://polymer.github.io/polymer/ for the base.

    enum Direction { horizontal, vertical }
    class SelectionGroup {
      @override
      Object deserializeValue(String value, Object currentValue, dynamic type) {
        return (currentValue is Direction)
            ? deserializeDirection(value)
            : super.deserializeValue(value, currentValue, type);
      }

      @override
      String serializeValue(Object value) {
        return (value is Direction)
            ? serializeDirection(value)
            : super.serializeValue(value);
      }
    }

Doing this is currently unavailable in the 0.17 branch.

**Comment by donny-dont** [comment]
@jakemac53 is there any way in particular you'd like this approached?

**Comment by jakemac53** [comment]
I think it should be special cased, similar to the lifecycle methods here https://github.com/dart-lang/polymer-dart/blob/0.17-0-dev-interop-reverse/lib/src/common/polymer_descriptor.dart#L113. In fact, you may just be able to add `#deserialize` and `#serialize` to the `_lifecycleMethodOptions` QueryOptions object. We may want to rename it at that point though.

**Comment by donny-dont** [comment]
Okay cool was eyeballing those as a potential approach. Thank you sir!

**Comment by jakemac53** [comment]
Another thing I was just thinking about is the ability to call `super.deserialize` from within these methods. We could define versions on the PolymerMixin class, which call Polymer.Base.deserialize via js interop, but would come at a fairly steep cost (all calls to deserialize/serialize would go from js -> dart -> js, even if you didn't override it in your own class). Maybe we should just provide a helper or something along those lines, which doesn't actually live on the mixin class.

**Comment by donny-dont** [comment]
Hmmm. How about a mixin so you could do `with PolymerSerialize` if you need those things?

**Comment by jakemac53** [comment]
Actually I like that idea, seems reasonable.

**Comment by donny-dont** [comment]
I'm close the issue I'm sorting out now is getting back the Type in desrialize. It'd be easier if there was a deserializeValueFromAttribute function, but that's not the case. serialize is working fine though.

**Comment by donny-dont** [comment]
Added a commit to my local branch if you want to see if I'm going in the right direction, https://github.com/donny-dont/polymer-dart/commit/d898fe98dd02e523df860d5bf0f3287987355a98

if you have any ideas on how to handle getting the Type back I'd be interested to hear them. This would be easier if the attribute name was in the call.

I think it might work if dartValue was seeded with some type info when the proxy is being created. The reason being that deserialize is called before the property is set. At which point there's zero type info.

Maybe just building a simple JsObject that has a __dartType__ field or something. Not sure how that would work with the eventual using a Dart component in JS land though.

Let me know if you have any ideas @jakemac53

**Comment by jakemac53** [comment]
Looks like you are on the right track. I think the issue with the types comes from this https://github.com/dart-lang/polymer-dart/blob/0.17-0-dev-interop-reverse/lib/src/common/polymer_descriptor.dart#L206. We are always just passing in a type of Object for any unknown type. We could instead pass in Object for Map/JsObject, and otherwise just pass the dart type directly? I don't know if this would cause any errors on the polymer js side, but it probably won't. Then you should get the actual dart type back in deserialize.

**Comment by donny-dont** [comment]
@jakemac53 not sure why this didn't automagically close when #534 was merged. We good to close this?
