### ISSUE TITLE
Property name added twice in _buildJsContructorForType within JsProxy

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/polymer-dart#531]
When using abstract mixins on a PolymerElement a property name can end getting added twice which results in `Exception: TypeError: Cannot redefine property: x`.

    class LinearSelectable {
      String get direction;
    }
    class SelectionGroup extends PolymerElement with LinearSelectable {
      @property
      String direction;
    }

In this case the call to `smoke.query` contains the value direction twice, with the following values. 

    // LinearSelectable
    (mirror-based-declaration Symbol("direction") (property) final [])
    // SelectionGroup
    (mirror-based-declaration Symbol("direction") (field) [Instance of '_Override', Instance of 'Property'])

It then throws on `context['Object'].callMethod('defineProperty', ...)`.

Open to fixing this just wasn't sure if this was a smoke problem or a polymer problem.

This is through the useMirrors path.

**Comment by jakemac53** [comment]
Interesting, @sigmundch what do you think? Should smoke only return the property from `SelectionGroup` in this case?

**Comment by sigmundch** [comment]
mmm good question.

On one hand, smoke's queries were originally designed to return all matching definitions and not just what would be visible with a lookup. On the other hand, I can't think of any use case for the current behavior :)

So while I'm not opposed to changing it in smoke, I am more inclined to have the fix in the polymer side of things.

**Comment by donny-dont** [comment]
I can attempt a patch and if it'd be useful to do something like an `excludeOverriden` you could cherry pick it for smoke.

That work for everyone?

**Comment by sigmundch** [comment]
sgtm

**Comment by jakemac53** [comment]
Sgtm as well

**Comment by donny-dont** [comment]
One thing that would probably make this easier is if there was an isAbstract on the smoke declaration. Then you could just ignore anything that's abstract.

I have a branch that's doing this which seems to do the trick. Can push that and open a pull request if that works.

    /// Removes any overriden declarations from a smoke query.
    List<smoke.Declaration> _removeOverriden(List<smoke.Declaration> declarations) {
      var remove = [];
      var declarationCount = declarations.length;

      // Search for duplicates
      //
      // This assumes that smoke is recursively going into the parent classes and
      // gathering info before the child class. It then searches for a symbol with
      // the same name. If it finds it then it marks the indice for removal.
      for (var j = 0; j < declarationCount; ++j) {
        var symbol = declarations[j].name;
        for (var i = j + 1; i < declarationCount; ++i) {
          if (symbol == declarations[i].name) {
            remove.add(j);
            break;
          }
        }
      }

      // Go backwards through the list so that the indices are valid
      var removeCount = remove.length;

      for (var i = removeCount - 1; i >= 0; --i) {
        declarations.removeAt(remove[i]);
      }
    
      return declarations;
    }

**Comment by jakemac53** [comment]
> One thing that would probably make this easier is if there was an isAbstract on the smoke declaration. Then you could just ignore anything that's abstract.

You can override non-abstract things as well, so I think what you have is probably better.

> I have a branch that's doing this which seems to do the trick. Can push that and open a pull request if that works.

That sounds good, but since it does rely on the order of declarations I think it should live under the smoke package. I would add an option like `excludeOverriden` to `QueryOptions` [here](https://github.com/dart-lang/smoke/blob/master/lib/smoke.dart#L97), and then you will have to add support for that in the various implementations, but they should be able to share a common helper function (you can just search for `implements TypeInspectorService` in the repo).

**Comment by donny-dont** [comment]
Sounds good I'll open an issue on smoke and start hacking on it.
