### ISSUE TITLE
Start migration to reflectable package instead of smoke

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#535]
We should be able to migrate to the new [reflectable](https://github.com/dart-lang/reflectable/) package and away from smoke. This should lighten the load on the polymer transformer significantly, and possibly eliminate the need for a polymer transformer altogether.

See [this test](https://github.com/dart-lang/reflectable/blob/master/test_reflectable/test/polymer_basic_needs_test.dart) for an example of how to use the package.

**Comment by jakemac53** [comment]
note: this will require a github dependency for now as it is not yet published (it is not feature complete)

**Comment by eernstg** [comment]
Hi,

we'll publish the reflectable package really soon. I'm on vacation for a few more days now, but we intend to publish the package even though some features are not yet implemented, exactly because this would make it possible for you to get started.

**Comment by jakemac53** [comment]
I am also fine with a github dependency for the short term. At least until we make an actual release using this which wouldn't be for a little while. I am fine with waiting until we are ready and then requesting a real release of reflectable at that point?

**Comment by eernstg** [comment]
I think it makes sense for a pre-1.0 release to be incomplete as long as it
does what some core users of the package want, and then we'll use the
feedback when prioritzing what to do next. In any case, it won't create any
immediate problems for you if you have a github dependency and we publish
the package. You'll just make the decision about which way you want to get
it (the github dep. would provide a slightly more bleeding edge version,
the published one would be a bit more stable). So I think we can just
proceed as planned, all of us. ;-)


On Tue, Jul 14, 2015 at 4:10 PM, Jacob MacDonald <notifications@github.com>
wrote:

> I am also fine with a github dependency for the short term. At least until
> we make an actual release using this which wouldn't be for a little while.
> I am fine with waiting until we are ready and then requesting a real
> release of reflectable at that point?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/polymer-dart/issues/535#issuecomment-121249283>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by joo** [comment]
+eernstg

**Comment by jakemac53** [comment]
blocked on reflectable transformer work

**Comment by jakemac53** [comment]
marking as done since all polymer work is finished, just waiting on a few final things from the reflectable transformer
