### ISSUE TITLE
Problem dynamically inserting paper elements

### ISSUE THREAD

**Issue by Javier-Esteban** [dart-lang/polymer-dart#536]
Hi,
I'm having problems when dynamically inserting paper elements in HTML in Dart.
I am knew with dart and polymer, maybe this isn't the forum to post it...., or it's so an easy question that nobody else needed to post it...

I have to add content dynamically to my page, because it depends on users input, so I can't use template-repeat.
When I try the code in Dartium, it works perfectly,but with another browser like IE or Firefox, paper elementes injected are simply ignored.

A simple example of what I mean....
template

    <paper-action-dialog id="dialog" backdrop autoCloseDisabled layered="false">
      <p>xxxxxxxxx</p>
      <paper-button affirmative autofocus>Tap me to close</paper-button>
    </paper-action-dialog>

dart code
PaperActionDialog get dialog => $['dialog'];

When something happens...
dialog.appendHTML('<paper-checkbox></paper-checkbox>');
dialog.toggle();

I hope someone could help me....
Thanks in advance
Best Regards

**Comment by Javier-Esteban** [comment]
<paper-checkbox></paper-checkbox>
Is what I append to dialog.appendHTML

**Comment by zoechi** [comment]
Issues here in the GitHub repo are for bug reports. 
SO is a good place for questions or https://groups.google.com/a/dartlang.org/forum/#!forum/web 
See https://www.dartlang.org/support/ for more options. 
The Slack channel is monitored most of the time.

I guess what you want to do is 
- http://stackoverflow.com/questions/20474071
- and maybe http://stackoverflow.com/questions/25962986

**Comment by Javier-Esteban** [comment]
Thank you very much, I'm going to try as soon as possible.
Still I can't understand very well why I have to use "new Element.tag" in order to inject a paper-element inside HTML for IE and Firefox and it works without it in Dartium... It's not a new polymer element I'm creating, is a core polymer element....

**Comment by jakemac53** [comment]
The default sanitizer used by appendHtml no longer allows custom element tags, are you seeing any errors in the console?

**Comment by Javier-Esteban** [comment]
Well, jakemac53, My first aproach was showing a warning in the console:
Removing disallowed element <PAPER-CHECKBOX>
but I didn' t saw it, ups....
zoechi, 
Element papercheckbox = new Element.tag("paper-checkbox");
tdResultado.append(papercheckbox);
Worked for me, thank you very much.
It also worked for me:
PaperCheckbox pc = new PaperCheckbox();
        tdResultado.append(pc);
