### ISSUE TITLE
2 way data biding doesn't work with Complex objects?

### ISSUE THREAD

**Issue by Javier-Esteban** [dart-lang/polymer-dart#537]
Hi,
 I have used the example Binding to a Complex Object.(https://github.com/dart-lang/polymer-dart-patterns/tree/master/web/basics/binding_to_a_complex_object)
 I have done a Little change, I have add the following function to "my_element.dart"
 void changeName(){
 person.name.first="Peter";
 print ("new name: " + person.name.first);
 }
 And I have added a button to "my_element.html"
 [open tag]button on-click="{{changeName}}"[close tag]click [open tag]/button[close tag]

The print shows that person.name have been changed, but the two way data binding is not working and the HTML keeps the original name Kathy.

Two-way data binding doesn't work with complex objects?

Thanks in Advance

**Comment by DisDis** [comment]
Hi.
2-way binding work for only Observable object.
Please extends Person.

**Comment by Javier-Esteban** [comment]
Sorry, I'm really noob with dart and polymer....
Please, could you provide the code with the modification?

**Comment by DisDis** [comment]
class TestComplex1 extends Observable{
@observable
 int fieldInt1 = 1;
@observable
 TextComplex2 field2 = new TextComplex2();
}

class TextComplex2 extends Observable{
 @observable
 String name = TextComplex2";
}

**Comment by Javier-Esteban** [comment]
Thanks a lot!!!
