### ISSUE TITLE
Simple Polymer app fails on Safari iOS9 Beta

### ISSUE THREAD

**Issue by markhats** [dart-lang/polymer-dart#538]
All Polymer apps seem to be failing on Safari on iOS Beta 3 (public). I have uploaded a simple app exhibiting the failure and also images detailing the sequence of errors:
http://www.autograph-maths.com/OnTapTest.zip

![error1](https://cloud.githubusercontent.com/assets/3472245/8799995/b0143044-2fa6-11e5-84c6-58889e4f43c4.png)
![error2](https://cloud.githubusercontent.com/assets/3472245/8799999/b40f5bb0-2fa6-11e5-9bcf-1cf2d9f5f0ae.png)
![error3](https://cloud.githubusercontent.com/assets/3472245/8800000/ba47b450-2fa6-11e5-9848-e16d4b35db26.png)
![error4](https://cloud.githubusercontent.com/assets/3472245/8800001/bf60f7e4-2fa6-11e5-8e5f-4bc44a6aa4c0.png)

The app can be viewed at: http://www.autograph-maths.com/ontaptest/ontaptest.html

The online Polymer samples also all seem to fail, although I'm unsure if it's the same problem:
https://www.dartlang.org/samples/

It may also be an issue with Safari in OSX El Capitan Beta.

Hope someone is still reviewing Polymer bugs with the current version and all the effort is not with the new version.

**Comment by markhats** [comment]
Just downloaded iOS9 Beta 4 and it still has the same problem.

polymer.js (0.5) seems to work fine so it must be a polymer.dart issue.

Anyone looking into this?

**Comment by miroslavolek** [comment]
This is issue also on Safari 9 on desktop, it fails with same error:

TypeError: Attempting to change configurable attribute of unconfigurable property.
definePropertywebcomponents.min.js:10:1601
rwebcomponents.min.js:10:1601
(anonymous function)webcomponents.min.js:11:19945
(anonymous function)webcomponents.min.js:11:20082

etc.

**Comment by miroslavolek** [comment]
It appears that problem is in outdated web_components, i got it all working on iOS 9 and OSX 10.11 by overriding web_components in my yams file by adding:

dependency_overrides:
     web_components: "^0.12.0+3"

**Comment by enyo** [comment]
Thanks @miroslavolek that solved the problem.

I can also confirm: polymer `0.16.3+3` does *not* work on Safari iOS9 or El Capitan.

Forcing the `web_components` upgrade does the trick.

**Comment by davenotik** [comment]
Adding  `web_components: "^0.12.0+3"` to `dependency_overrides` gets that version but `pub build` then results in this whacky error:

```
Pub build errors: Could not find asset web_components|lib/README.md. package:pub/src/barback/pub_package_provider.dart 112 PubPackageProvider._assertExists package:pub/src/barback/pub_package_provider.dart 106 PubPackageProvider.getAsset.<async> This is an unexpected error. Please run pub --trace build --mode=debug and include the results in a bug report on http://dartbug.com/new.
```

Dart SDK: 1.12.2, Polymer 0.16.3+3

**Comment by davenotik** [comment]
Ah, it seems this is only with `pub build --mode=debug`! The regular `pub build` worked and that override fixed things on Safari. Thank you!
