### ISSUE TITLE
Object binding to an attribute doesn't work if @HtmlImport is used

### ISSUE THREAD

**Issue by vsheyanov** [dart-lang/polymer-dart#55]
I made 2 versions of the same test application.
First one uses @HtmlImport:
https://gist.github.com/vsheyanov/349d8210f566b80b5e25

Second one uses **link rel="import"**
https://gist.github.com/vsheyanov/8ef3ca894610d5aa7760

In both examples there is a parent-component
```
<polymer-element name="parent-component">
    <template>
        <child-component selectedValue="{{selectedValue}}"></child-component>
    </template>
```
and child component
```
<polymer-element name="child-component">
    <template>
        Value: {{selectedValue.label}}
    </template>
</polymer-element>
```
Problem is that when @HtmlImport is used, object **selectedValue** is not bound properly to child-component.
Instead of passing DataVO object to selectedValue attribute it passes string '[DartObject object]'.
This leads to an exception
```
Exception: Uncaught Error: Error evaluating expression 'selectedValue.label': Class 'String' has no instance getter 'label'.
NoSuchMethodError: method not found: 'label'
Receiver: 
Arguments: []
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _LocalInstanceMirror._invokeGetter (dart:mirrors-patch/mirrors_impl.dart:549)
#3      _LocalInstanceMirror._getFieldSlow (dart:mirrors-patch/mirrors_impl.dart:466)
#4      _LocalInstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:480)
#5      ReflectiveObjectAccessorService.read (package:smoke/mirrors.dart:26:63)
#6      read (package:smoke/smoke.dart:30:39)
```

In child component I've added change handler and for @HtmlIImport it logs **String** which is wrong, but when **link rel="import"** is used it logs **DataVO** which is right and everything works fine.

**Comment by jakemac53** [comment]
This is actually due to the ordering of the imports, in the @HtmlImport version you have dart imports that look like the following:

```dart
import 'parent_component.dart';
import 'child_component.dart';
```

and in the regular html import version you have this:

```html
<link rel="import" href="child_component.html">
<link rel="import" href="parent_component.html">
```

Notice that in the dart one you put the `parent_component` before the `child_component`. This means that the parent will be registered before the child. We could probably work on giving nice errors in this case though.

**Comment by vsheyanov** [comment]
@jakemac53 thanks a lot. Fixing import order did the trick.
Is there any recommendation how to handle imports cause I'm guessing having many imports will increase chances of breaking import order.

**Comment by vsheyanov** [comment]
Actually there is a warning: 'Attributes on app-header were data bound prior to Polymer upgrading the element. This may result in incorrect binding types.'
I just didn't realize what was causing this warning

**Comment by jakemac53** [comment]
The safest thing is to have an import to all of your dependencies at the top of each file. For instance in your app if you added `import 'child_component.dart';` to your `parent_component.dart` it would have worked fine.

This is partly my fault for having a bad example in the polymer spa tutorial with the separate file that includes all of an apps element imports. While it does reduce the total number of imports necessary it can easily bring up issues like this. It is safer in general to just add all imports to all files manually.

**Comment by jakemac53** [comment]
Maybe updating that existing warning would be enough. I would really like it to say something like `child-component appears in the template for parent-component but parent-component was registered first. This may result in incorrect binding types.`
