### ISSUE TITLE
Design/implement behaviors api

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#551]

**Comment by donny-dont** [comment]
Is this something separate from https://github.com/dart-lang/sdk/issues/23770 ? It seemed like that would fix the issues.

**Comment by jakemac53** [comment]
If we decide to wait for it, then yes the design can probably use that feature. We also need to explore how this will interact with the behaviors written in JS. I have a feeling its going to end up being more complicated.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/polymer-dart/pull/557 is the first step towards this. In some ways the api actually is better than using the super calls in mixins proposal, as it guarantees that all lifecycle methods will be called, regardless of whether you call `super`.

**Comment by jakemac53** [comment]
This has turned out to work quite well, so I think it will be the final implementation, at least until we have the super call in mixins support at which point we can evaluate migrating to that. For the reason stated above I am actually inclined not to ever migrate though.

**Comment by jakemac53** [comment]
blocked on reflectable transformer work

**Comment by DisDis** [comment]
Hi @jakemac53 .
Is there a chance to run a minimal example this week?
Currently tests are falling due reflectable. (UnimplementedError in declarationsFor)
I am concerned about performance for List, Map. A simple example for the List (change / add / remove) can help.

**Comment by jakemac53** [comment]
I think the reflectable work is probably a couple weeks out still unfortunately. You can run in dev mode though (in dartium, not through pub serve)

**Comment by DisDis** [comment]
Thanks for the answer.
I very much hope that the alpha version will be in our hands by the end of August.

I use the branch 'behaviors'.
I'm run:
pub serve
dartium

My minimal example (property_binding.dart) is not working.
Do you have a minimum working example with bindings?

**Comment by jakemac53** [comment]
If you are on the behaviors branch, then don't run `pub serve`. Instead just start any local server at the top level dir of your package, and access it that way. Pub serve runs the transformers which are not yet fully implemented (hence the errors you are getting).

**Comment by DisDis** [comment]
Thanks.
I'll try.

**Comment by jakemac53** [comment]
Closing this, its still blocked from being merged in until reflectable transformer is more fully implemented, but everything works in development mode.
