### ISSUE TITLE
selectItem and setItemSelected methods do not work

### ISSUE THREAD

**Issue by rvaleev** [dart-lang/polymer-dart#554]
Example exception:
Exception: Uncaught Error: RangeError (index): Invalid value: Only valid value is 0: 4
Stack Trace:
```dart
#0      List.[] (dart:core-patch/growable_array.dart:136)
#1      ObservableList.[] (package:observe/src/observable_list.dart:90:49)
#2      CoreList.selectItem (package:core_elements/core_list_dart.dart:1192:20)
```

Looks like the once who did introduce grouping haven't tested that part.

core_elements: version: "0.7.1+2"
polymer: version: "0.16.3+3"

```html
<core-list-dart id="list" data="{{data}}" selection="{{selection}}" fit>
	<template>	
....
	</template>
</core-list-dart>
```

**Comment by jakemac53** [comment]
If this is still an issue please refile on the core-elements repo
