### ISSUE TITLE
Behaviors should allow  you to add host attributes

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#561]
Possibly just a static field would be best for this.

**Comment by jakemac53** [comment]
@sigmundch not sure if you have an opinion here, its a bit weird because for regular elements its a part of the @PolymerRegister annotation. We will actually be dropping the @behavior annotation entirely in the future (most likely), so I don't really want to tie any behavior into it. Static const field on the class seems like the best solution in lieu of that?

**Comment by sigmundch** [comment]
it would be nice to have both consistent though. Would it make sense to move hostattribtes out of `PolymerRegister` and make them static const fields there too? Or, what if you use `@behavior` only when you need to register a host attribute?

**Comment by jakemac53** [comment]
Or adding `@HostAttributes` as a separate annotation which can be applied to polymer elements AND behaviors?

**Comment by sigmundch** [comment]
that could be

**Comment by jakemac53** [comment]
Added it as a static field on classes, as that allows support for non-const objects as well (such as DateTime). Implemented in d36e04a28456775177b34c1f5a4e6fd21634d0c0
