### ISSUE TITLE
Edit Wiki | Feature Overview

### ISSUE THREAD

**Issue by damondouglas** [dart-lang/polymer-dart#568]
Is this an acceptable edit for [Feature Overview](https://github.com/dart-lang/polymer-dart/wiki/feature-overview)?

The Polymer library provides a set of features for creating custom elements. These features are designed 
to make it easier and faster to make custom elements that work like standard DOM elements. Similar to standard DOM elements, Polymer elements can be:

* Instantiated using a constructor or `document.createElement`.
* Configured using attributes or properties.
* Populated with internal DOM inside each instance.
* Responsive to property and attribute changes (for example, by populating data into the DOM, or firing an event).
* Styled with internal defaults or externally.
* Responsive to methods that manipulate its internal state.

A basic Polymer element definition looks like this:

element_name.html:

```html
<dom-module id="element-name">
  <style>
    /* CSS rules for your element */
  </style>
  <template>
    <!-- local DOM for your element -->
    <div>{{greeting}}</div> <!-- data bindings in local DOM -->
  </template>
</dom-module>
```

element_name.dart:

```dart
@HtmlImport('element_name.html')
library my_package.element_name;
    
import 'package:polymer/polymer.dart';
import 'package:web_components/web_components.dart' show HtmlImport;

@PolymerRegister('element-name')
class ElementName extends PolymerElement {
  ElementName.created() : super.created();
      
  @property
  String greeting = 'Hello!';
}
```

This guide divides the features into the following groups:

*   [Registration and lifecycle](registration-and-lifecycle). Registering an
    element associates a class (prototype) with a custom element name. The
    element provides callbacks to manage its lifecycle. Use behaviors to
    share code.

*   [Declared properties](properties). Declared properties can be 
    configured from markup using attributes. Declared properties can optionally
    support change observers, two-way data binding, and reflection to attributes.
    You can also declare computed properties and read-only properties.

*   [Local DOM](local-dom). Local DOM is the DOM created and managed by the element.

*   [Events](events). Attaching event listeners to the host object 
    and local DOM children. Event retargeting.

*   [Data binding](data-binding-syntax). Property bindings. Binding to attributes.

*   [Behaviors](behaviors). Behaviors are reusable modules of code that can be 
    mixed into Polymer elements.

*   [Utility functions](utility-functions). Helper methods for common tasks.

*   [Experimental features and elements](experimental). Experimental template and styling features.
    Feature layering.

If you're migrating an existing 0.5 element to the new APIs, see the [Migration guide](migration)
for advice.

**Comment by jakemac53** [comment]
I do like the wording a bit more, but there is also something to be said for changing it as little as possible from the original docs (makes bringing over new changes easier). I think it is probably ok to diverge though.

I don't have a lot of experience with github wikis, do you have the ability to edit the existing overview or send a pull request of some sort?

**Comment by donny-dont** [comment]
@jakemac53 just a heads up on a dartdoc issue that i think would be of interest here https://github.com/dart-lang/dartdoc/issues/72. Then you could technically have multiple .md files that go over stuff and that'd end up in the dartdoc rather than hanging out in a github wiki.

**Comment by jakemac53** [comment]
Interesting, we can look into that once its available. For now I think the wiki is ok, and its easy to move stuff out of it if needed.

**Comment by donny-dont** [comment]
I was figuring if it was useful to Polymer maybe it'd get a boost in priority on the dartdoc side :wink:

**Comment by damondouglas** [comment]
@donny-dont great idea.  @jakemac53 I do have access to edit and save but felt scared to change it :)
