### ISSUE TITLE
Access to `dataHost` in `dom-bind`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#574]
I would like to set model data like discussed in http://stackoverflow.com/questions/30855739/templateinstance-model-in-polymer-1-0
I haven't found a way to do this

**Comment by zoechi** [comment]
It seems this is not how it is supposed to work. The Polymer.js `dom-bind` tests assign to any property. 
```html
<template id="t" is="dom-bind">
  <div>Model: <span>{{model}}</span></div>
<template>
```
```dart
main() async {
  await initPolymer();
  var template = document.querySelector('#t') as DomBind;
  var templateJs = template.jsElement;
  templateJs['model'] = new MyModel();
}

class MyModel extends JsProxy {
  String value = 'something';
  @eventHandler
  buttonTap() {
    print($['mybutton'].id);
    print('tap!');
  }
}
```
Shows
> [object DartObject]

But I wasn't able to get properties shown.
```html
<span>{{model.value}}</span>
``` 
doesn't produce any output.

**Comment by jakemac53** [comment]
Try replacing:

```dart
templateJs['model'] = new MyModel();
```

with:

```dart
templateJs['model'] = jsValue(new MyModel());
```

If that works we can easily update the DomBind wrapper to do this automatically

**Comment by zoechi** [comment]
Yup, this shows the model value when the page is loaded
```html
<div>Say something: <input value="{{model.value}}"></div>
<div>You said: <span>{{model.value}}</span></div>
```
the input element and the `<span>` show `something`. 
But when I change the value in the input field, the text in `span` is not updated.

I also tried to define an event handler
```dart
@jsProxyReflectable
class MyModel extends JsProxy {
  String value = 'something';

  buttonTap(e) {
    print('tap!');
  }
}
```
```html
<button id="mybutton" on-click="model.buttonTap">Tap me!</button>
```
but I only get
>  [dom-bind::_createEventHandler]: listener method `model.buttonTap` not defined

in the browser console.

**Comment by jakemac53** [comment]
> But when I change the value in the input field, the text in span is not updated.

See [the wiki](https://github.com/dart-lang/polymer-dart/wiki/data-binding-syntax#two-way-binding-to-native-elements). In the new polymer to get two way binding with native elements you need to add `::eventName` to the binding, which causes it to listen for those events and update the value.

For instance, you could use the `change` or `input` events to update the binding:

```html
<div>Say something: <input value="{{model.value::change}}"></div>
```

> but I only get
> > [dom-bind::_createEventHandler]: listener method model.buttonTap not defined

> in the browser console.

Afaik this isn't supported (setting up event to call a method on the model). The methods would need to be added to the dom-bind instance itself, which could only be done today via js interop, something like this:

```dart
templateJs['buttonTap'] = ([_, __]) {
  print('tap!');
};
```

This is obviously not ideal though, not sure what the best way would be to deal with it. One option could be adding a `addEventHandler(String name, Function handler)` method to the DomBind wrapper?

**Comment by zoechi** [comment]
Just saw you comment at https://github.com/dart-lang/polymer-dart-patterns/pull/33/files#r39408809
adding `::change` makes the text in `<span>` update.

```html
<div>Say something: <input value="{{model.value::change}}"></div>
<div>You said: <span>{{model.value}}</span></div>
```

The event handler still doesn't work. Continue reading your comments ... ;-)

**Comment by jakemac53** [comment]
@zoechi @sigmundch what do you think about overriding the `[]` operator for the DomBind wrapper, to just automatically assign to the jsProxy after calling `jsValue`? This would allow you to add any properties you wish, and use them in the template.

**Comment by zoechi** [comment]
I got it working. Thanks a lot for your support :)
I guess overriding `[]` would be a nice feature and would make it obvious how to use `dom-bind` imperatively.
I can live with event handlers added to the `dom-bind` instance. I want to use `dom-bind` only for simple examples and unit-tests. In real applications I always use an `app-element`.

**Comment by jakemac53** [comment]
Yes I agree that creating an app-element is generally better practice, but I do want to support `dom-bind` as well since it is nice for some situations (like tests/examples as you pointed out).
