### ISSUE TITLE
Setting attributes of iron-dropdown in HTML doesn't work

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#578]
Polymer.dart 0.17 
None of these properties (except id)
```html
<iron-dropdown id='years-dropdown'
                   horizontalAlign="right"
                   verticalAlign="bottom"
                   positionTarget="[[getElement('dropdown-button')]]"
                   verticalOffset="100">
```
are set to the assigned values when I check from the debugger (Dartium) at [this line](https://github.com/bwu-dart-playground/polymer1/blob/master/core_dropdown_item_label/web/app_element.dart#L23) (all are set to their defaults)
[Full example project](https://github.com/bwu-dart-playground/polymer1/blob/master/core_dropdown_item_label/web/app_element.html#L31)

When I set it from code (as I did in `openDropdown()` then it works as expected.

**Comment by jakemac53** [comment]
The issue here is that you have to convert to hyphen separated names instead of camelCase. So `horizontalAlign="right"` becomes `horizontal-align="right"` etc.

**Comment by jakemac53** [comment]
see https://github.com/dart-lang/polymer-dart/wiki/properties#property-name-to-attribute-name-mapping

**Comment by zoechi** [comment]
I thought that was what I tried first. The wiki is great help but it's quite a lot of new info to process... 
I'll try again and reach out again if it still doesn't work. Thanks!

**Comment by jakemac53** [comment]
Yes, there is a lot :(. Working on more/better documentation.

**Comment by zoechi** [comment]
Works fine, sorry for the noise. The other attributes (horizontal-align, vertical-align, vertical-offset) caused the problem when set correctly :D Have yet to investigate further how to correctly use them.

**Comment by jakemac53** [comment]
Not completely following you, which problem do they cause?

**Comment by zoechi** [comment]
Just a user problem. Seems the values I used didn't make sense and led to unexpected results. Too much trial and error  for one day I guess. The docs for JS xxx-elements are still quite shallow.
