### ISSUE TITLE
Polymer should export `HtmlImport`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#588]
Polymer should export `HtmlImport` from `web_components`.

``` dart
import 'package:web_components/web_components.dart' show HtmlImport;
import 'package:polymer/polymer.dart';
```

I find it quite cumbersome to always add the `web_components` import in addition to the `polymer` import to make `@HtmlImport(...)` work.

It might not be the best practice to export a class from another package but I think it's worth considering, or maybe you know a better alternative.

**Comment by jakemac53** [comment]
We used to do this, and I think I agree that we should add it back. I wanted to avoid exporting things from other packages in the new version, but I think I will make an exception for `HtmlImport` since its used by almost every polymer element.
