### ISSUE TITLE
After `pub build` JS script tag is not added in output `index.html`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#593]
After changing `<script type="application/dart" src="index.bootstrap.initialize.dart"></script>` for example in `build/web/google_analytics/index.html` to
<script src="index.bootstrap.initialize.dart.js"></script>
the page works fine in Chrome.

**Comment by jakemac53** [comment]
Yes, this is working as intended for now at least. You can add the `<script src="packages/browser/dart.js"></script>` script below your dart script and it will swap it at runtime (thats what we do in the tests) but it isn't ideal for deployment.

**Comment by jakemac53** [comment]
Really there should be a separate package which does this in a general fashion

**Comment by jakemac53** [comment]
fwiw there is this https://pub.dartlang.org/packages/dart_to_js_script_rewriter but I have never used it

**Comment by zoechi** [comment]
Ups, I forgot that `browser/dart.js` needs to come after the Dart script tag.
Didn't do much client side Dart the recent year.
dart-lang/pub#779
