### ISSUE TITLE
Can't read properties of event.details (sent from JS)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#596]
In the JS demo `event.details` looks like:
```
Object {keyboardEvent: KeyboardEvent}
> keyboardEvent: KeyboardEvent
v __proto__: Object
  combo: "pageup"
  event: "keydown"
  key: "pageup"
  __proto__: Object
```

in Dart
```
v {keyboardEvent: Instance of 'KeyboardEvent'}
  > [[class]]: _InternalLinkedHashMap
```
sent from https://github.com/PolymerElements/iron-a11y-keys/blob/master/demo/x-key-aware.html#L49

I can access `event.detail['keyboardEvent'] but `event.detail['combo'] doesn't work in Dart (works fine in the JS example)

Any idea how to get access to the `combo` item?

**Comment by jakemac53** [comment]
I have a feeling it might just need to be updated, also if the detail object is actually another event and they set custom properties on it from JS then you would need to do something like:

```new JsObject.fromBrowserObject(e.detail['keyboardEvent'].original)['combo']```

We could possibly automate this in the CustomEventWrapper object though (it is already abstracting away some of the `event.detail` madness from you)

**Comment by zoechi** [comment]
I tried that. 
`combo` isn't a property on `KeyboardEvent` but another item in the map (sibling to `keyboardEvent`) but added to `__proto__` (my interpretation from my limited JS knowledge) and not accessible from the Dart side.
in JS `event.detail.combo` returns `pageup`. In Dart `event.detail['combo'] returns `null`.

**Comment by jakemac53** [comment]
Ok, so this should work: `convertToJs(event.detail)['combo']` (`jsValue` instead of `convertToJs` if you are on the 0.2.0-dev branch of polymer_interop). Basically `convertToJs` gives you the original JsObject that the map was created from.

Long story short it looks like they are hot swapping the prototype of the object without actually creating a constructor, and that breaks some assumptions in `convertToDart` so the dart map we create doesn't contain things from the prototype.

**Comment by jakemac53** [comment]
Edit: they aren't hot swapping they are creating it with `Object.create(proto)`. When you do that the constructor is still `Object`, so we think its a normal object and go ahead and create a map out of it. We should be checking that the `__proto__` is equal to `Object.prototype` instead.

**Comment by jakemac53** [comment]
should be fixed now (although not verified)

**Comment by zoechi** [comment]
Yup, works fine :)
