### ISSUE TITLE
`fire` from `PolymerBase` doesn't convert `detail`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#604]
While porting iron-signals I have this code
```dart
fire('iron-signal', detail: convertToJs({'name': "foo", 'data': "Foo!"}));
```
Without `convertToJs(...)` `iron-signals` didn't recognize the event.

Does it make sense to automatically convert?

**Comment by jakemac53** [comment]
Definitely just a bug, thanks for the report!
