### ISSUE TITLE
When I launch a Polymer 1.0.0-rc1 entry point with a non-`pub serve` server, nothing is shown (`unresolved` is not removed)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#606]
The `unresolved` tag is not removed and the page stays blank (removing the `unresolved` attribute in devtools reveals the content). 
Elements are upgraded therefore Polymer seems to be initialized properly.
This is only when I run with a simple webserver. 
When I use `pub serve` it works fine.
This is with all polymer_element examples.
Any idea what is missing?

**Comment by jakemac53** [comment]
Not sure exactly why this is, but if you move your `dom-module` tags into a separate file then it works fine. I think there was an issue about this somewhere (but couldn't find it), and it might already be fixed in the newer version of polymer.

**Comment by jakemac53** [comment]
actually I take that back, it doesn't seem to solve the issue

**Comment by zoechi** [comment]
Ok, I always create a new file for each element.
At least it seems you can reproduce.   
The script that should remove the unresolved tag seems to be imported but it's not executed or it is, but at the wrong time.

**Comment by jakemac53** [comment]
I will put in a hack for now at least to just manually remove this at the end of `initPolymer`.

**Comment by zoechi** [comment]
:+1:

**Comment by jakemac53** [comment]
now tracking in https://github.com/dart-lang/polymer-dart/issues/611
