### ISSUE TITLE
PolymerElement $ accessor return null on 1.0.0-rc.2

### ISSUE THREAD

**Issue by vgordievskiy** [dart-lang/polymer-dart#616]
@PolymerRegister('elemnt-test')
class ElementTest extends PolymerElement {
  ElementTest .created() : super.created();

 ready() {
    var test1 = this.$; // test1 is null
    var test2 = $['some-element-id']; // throw exc
 }

}

**Comment by jakemac53** [comment]
Hmm, this definitely works in general (see test [here](https://github.com/dart-lang/polymer-dart/blob/1.0.0-rc.2/test/src/standard/node_finding_test.dart), so something else is probably going on. Maybe `@PolymerRegister('elemnt-test')` is supposed to be `@PolymerRegister('element-test')` so its not finding the `dom-module` tag (or maybe thats just a type in the issue). If that is not it can you please post a full example?

**Comment by jakemac53** [comment]
also - this will only exist in `polymer.dart`, not in `polymer_mini.dart` or `polymer_micro.dart` (see feature list [here](https://github.com/dart-lang/polymer-dart/wiki/experimental-features#polymer-standard-features)).

**Comment by vgordievskiy** [comment]
Thanks) It is problem on my side.
Was in html - <dom-module id=="element-test">

**Comment by jakemac53** [comment]
Ah yep that makes sense. Unfortunately since a `dom-module` is not required we can't really add a check in to make sure that the tag name in PolymerRegister matches a dom-module either :(. Maybe the `$` getter could warn if it returns null though?

**Comment by vgordievskiy** [comment]
I think, that some error message on start are enough.

**Comment by jakemac53** [comment]
Unfortunately we would have to perform this check inside the `$` getter :/. At startup we don't know whether or a polymer-element is expecting to have a matching dom-module.

**Comment by vgordievskiy** [comment]
In this case a warning in $ getter will be good)
