### ISSUE TITLE
dom-repeat on table row doesn't display repeated rows

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#623]
dom-repeat on table row doesn't display any repeated rows.
```<table>
                    <thead>
                    <tr>
                        <th>name</th>
                    </tr>
                    </thead>
                    <tbody>
                    <template is="dom-repeat" items="{{data}}">
                        <tr>
                            <td>{{item.uname}}</td>
                        </tr>
                    </template>
                    </tbody>
                </table>```

**Comment by sigmundch** [comment]
@jakemac53 can provide more details when he returns from vacation, but my guess is that this might not be supported unless your browser implements `<template>` natively.

Here is a note copied from the polymer.js website, explained in their migration guide from polymer 0.5 (https://www.polymer-project.org/1.0/docs/migration.html#template-repeat):

> Note that browsers that do not support templates natively don’t allow `<template>` tags inside of `<table>` or `<select>` elements. Polymer 0.5 provided a workaround for this using the template attribute. There is no equivalent workaround for the new release at this point.

**Comment by terrywarwar** [comment]
I tried it in both Chrome and Chromium.

**Comment by jakemac53** [comment]
Simple example worked fine for me, maybe its just a typo `{{item.uname}}` => `{{item.name}}`? If that is not it then I would need a bit more info in order to help.

**Comment by terrywarwar** [comment]
No typo, the template works fine outside of a table.  I'm using it with an iron-ajax and bound to last-response="{{data}}".  I'll try it without iron-ajax and see if that make a difference.

**Comment by terrywarwar** [comment]
Changing it didn't make any difference.  This is the model used 
```class MyModel extends JsProxy {
  @reflectable String uname;
}```

It works fine when I use this template. 
```
<template is="dom-repeat" items="[[data]]">
    <div><span>[[item.uname]]</span></div>
</template>
```

**Comment by jakemac53** [comment]
Interesting, this appears to only be an issue post-transform. In mirrors mode it works fine.

**Comment by terrywarwar** [comment]
How do you enable mirrors mode, I tried removing my transformers but my app errors.

**Comment by jakemac53** [comment]
There isn't a transformer option for it, but you can just run a regular local server (not pub serve).

**Comment by terrywarwar** [comment]
Using mirrors worked for me also.

**Comment by jakemac53** [comment]
Great, I can work on the actual bug soon

**Comment by jakemac53** [comment]
weird, this actually looks like a package:html bug

**Comment by jakemac53** [comment]
https://github.com/dart-lang/html/issues/12 looks like the general tracking bug for this

**Comment by jakemac53** [comment]
As a workaround, I would just fake a table by styling normal elements as `display: table`, `display: table-row`, `display: table-cell`, etc.

**Comment by terrywarwar** [comment]
Thanks, that's what I ended up doing.

**Comment by jakemac53** [comment]
closing this in favor of dart-lang/html#12 and the workaround stated here

**Comment by fallenreaper** [comment]
I was taking a look at some code and was trying to do this.  I noticed the display:table-row etc to apply to divs, which is fine, but i was looking to leverage colspan which isnt done through css, so i thought it best to work with table/tr/td in order to handle colspan.  My desired endstate is to use a colspan to group a bunch of cells representing times as either AM or PM by doing colspan=12.  Seems the rows dont render though, so im trying to find an alternate option given 1 way doesnt render tr/td, and the other way doesnt support colspan.
