### ISSUE TITLE
DomRepeatModel.fromEvent using on-tap

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#624]
I'm getting the following error for an on-tap event when using DomRepeatModel.fromEvent(e), however works fine for an on-click event.

object must be an Node, ArrayBuffer, Blob, ImageData, or IDBKeyRange
#0      JsObject._fromBrowserObject (dart:js:550)
#1      JsObject.JsObject.fromBrowserObject (dart:js:528)
#2      DomRepeatModel.DomRepeatModel.fromEvent (package:polymer/src/template/dom_repeat.dart:121:21)
#3      MapView.onItemSelectedFromMulti (package:cpl_ami/map_view.dart:528:21)
#4      Function._apply (dart:core-patch/function_patch.dart:7)
#5      Function.apply (dart:core-patch/function_patch.dart:28)
#6      _InstanceMirrorImpl.invoke (package:reflectable/src/reflectable_transformer_based.dart:164:23)
#7      _setupReflectableMethods.<anonymous closure>.<anonymous closure> (package:polymer/src/common/polymer_descriptor.dart:152:31)

**Comment by zoechi** [comment]
```dart
new DomRepeatModel.fromEvent(convertToJs(event));
```
seems to work for `on-tap`.

**Comment by terrywarwar** [comment]
Thanks.

**Comment by jakemac53** [comment]
Reopening as this should be automatic

**Comment by zoechi** [comment]
This looks similar http://stackoverflow.com/questions/33156093/how-to-get-localtarget-in-listener-in-polymer-dart-1-0?noredirect=1#comment54145689_33156093
