### ISSUE TITLE
Polymer 1 Project works in Dartium but fails in Chrome

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#632]
When I load `web/index.html` in Chrome I get the exception when I select a demo from the left drawer:

> Uncaught TypeError: J.getInterceptor$asx(...).$index is not a function
> J.$index$asx @ init.dart:31
> (anonymous function) @ all_demos.dart:260
> (anonymous function) @ VM900:2
> dart.Primitives_applyFunctionWithPositionalArguments @ js_helper.dart:1457
> dart._InstanceMirrorImpl.invoke$3 @ js_helper.dart:1424
> dart._InstanceMirrorImpl.invoke$2 @ reflectable_transformer_based.dart:173
> dart._setupReflectableMethods__closure.call$2 @ polymer_descriptor.dart:161
> dart.Primitives_applyFunctionWithPositionalArguments @ js_helper.dart:1457
> dart._callDartFunction @ js_helper.dart:1424
> (anonymous function) @ js_dart2js.dart:106
> (anonymous function) @ index.html:1405
> handler @ index.html:4410
> decorated @ index.html:9109
> Polymer.Base._addFeature.fire @ index.html:5427
> Gestures.fire @ index.html:4814
> Gestures.register.forward @ index.html:5087
> Gestures.register.click @ index.html:5068
> Gestures.handleNative @ index.html:4693

https://github.com/bwu-dart/polymer_elements_demos/blob/master/web/all_demos.dart#L260

Works fine in Dartium bleeding edge.

**Comment by zoechi** [comment]
Same exception in Firefox 41.0.2

**Comment by jakemac53** [comment]
Ah so this is really a dart2js bug, you can fix it by wrapping the return value of `modelForElement` in a js object (with `new JsObject.fromBrowserObject(...)`)

**Comment by jakemac53** [comment]
Basically if a js object has `HTMLElement` anywhere on its prototype chain then dart2js thinks its an html element instead of just a normal js object.

**Comment by jakemac53** [comment]
This is also arguably a polymer js bug, since none of the methods from HTMLElement.prototype are going to be valid for the model object ;)

**Comment by jakemac53** [comment]
cc @jacob314 @sigmundch

**Comment by zoechi** [comment]
Thanks a lot for that workaround (works now) and your super-fast response :+1:
