### ISSUE TITLE
setting attribute "value" on input element via "value$=" throws InvalidCharacterError

### ISSUE THREAD

**Issue by hentoesch** [dart-lang/polymer-dart#638]
in one of my elements i have the following: 

"input id="data"  type$="{{typ}}"  value$="{{inputValue}}"  on-keyup="keyUp"

in polymer 1.0.0.rc2 this worked. 
in polymer 1.0.0.rc5 it throws the following error (value$= is the problematic part):

Exception: Uncaught Error: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'value$' is not a valid attribute name.
Stack Trace:
#0      JsObject._callMethod (dart:js:678)
#1      JsObject.callMethod (dart:js:618)
#2      PolymerRegister.initialize (package:polymer/src/common/polymer_register.dart:19:13)
#3      loadInitializers.<anonymous closure>.<anonymous closure> (package:initialize/src/static_loader.dart:46:32)
#4      _runInitQueue (package:initialize/initialize.dart:35:24)
#5      _runInitQueue.<anonymous closure> (package:initialize/initialize.dart:38:26)
#6      _RootZone.runUnary (dart:async/zone.dart:1166)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#9      _Future._completeWithValue (dart:async/future_impl.dart:368)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#12     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#13     _ScheduleImmediateHelper._handleMutation (dart:html:42567)

the place where this error happened was VERY hard to find, as the error message gave now hint.
how is this supposed to be done in a correct way?

**Comment by jakemac53** [comment]
It looks like for the `value` attribute you should not use `$=`. It does work for `href` and other properties still, just not `value`. I would file a bug on polymer js if you need to use attribute binding for the `value` attribute.

**Comment by jakemac53** [comment]
actually looks like its already filed, https://github.com/Polymer/polymer/issues/2666

**Comment by hentoesch** [comment]
so i have not been the first been bitten by this ... 
thanks.

**Comment by jakemac53** [comment]
ya, it seems to be isolated to the `value` attribute
