### ISSUE TITLE
Inserting an element to local DOM doesn't work 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#639]
```dart
  ready() {
    new PolymerDom(root).children.insert(0,
        new dom.Element.tag('style', 'custom-style')
      ..id = 'theme'
      ..attributes['include'] = theme != null ? 'default-theme' : theme);
    PolymerDom.flush();
  }
```
The style element (same with a `DivElement`) isn't inserted.
` new PolymerDom(root).append(` works though.

**Comment by jakemac53** [comment]
I think that this is working as intended. PolymerDom does not automatically wrap the return values of its methods in other PolymerDom objects, so modifying `.children` directly doesn't work. See https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#work-with-local-dom for an example of how to insert children.

**Comment by zoechi** [comment]
I guess I got it. Thanks for the hint.
