### ISSUE TITLE
$['id'] should return Element instead of js.JsObject

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#640]
```dart
abstract class PolymerBase implements CustomElementProxyMixin {
  /// The underlying Js Element's `$` property.
  js.JsObject get $ => jsElement[r'$'];
```
Is this intentional?
It breaks autocompletion.

**Comment by zoechi** [comment]
Same with remove

```dart
    new PolymerDom(root).querySelectorAll('[theme]').forEach((e) => e.remove());
    new PolymerDom(root).querySelectorAll('[theme]').forEach((dom.Element e) => new PolymerDom(root).removeChild(e));
```
This works when I switch to shadow DOM `...url?dom=shadow`

**Comment by jakemac53** [comment]
The `$` object itself is a `JsObject`. Unfortunately the JsObject class doesn't support generics so there isn't much we can do here :(.

**Comment by zoechi** [comment]
It seems it always can be cast to an `Element`. Are there exceptions?

**Comment by jakemac53** [comment]
The return value of the `[]` operator is always an `Element` yes, but I don't know of an automated way to deal with that (without wrapping the `$` object or something).

**Comment by kirbyfan64** [comment]
Would anyone be interested in a PR that adds something (maybe `$+`?) that wraps the cast to `Element`?

**Comment by zoechi** [comment]
Why can't you just change the return type from `js.JsObject` to `Element` when
on call-site `Element x = $['someid'];` seems to work fine.?

**Comment by jakemac53** [comment]
This getter is for `$`, which is a `JsObject` and not an `Element`. The `[]` operator of that object is what is returning the `Element`.

**Comment by zoechi** [comment]
Now I get it!
Sorry, too much debugging today :-/
`$` would need to return an instance of a class that wraps `JsObject` and implements `[]` so that calls are forwarded to the wrapped `JsObject` and declare a return type `Element`.
Do you think it's to expensive to create such an instance? I guess it would need only one per element instance?
