### ISSUE TITLE
Syntax error in wiki-example in "feature-overview"

### ISSUE THREAD

**Issue by flash1293** [dart-lang/polymer-dart#642]
The first dart-example on https://github.com/dart-lang/polymer-dart/wiki/feature-overview (element_name.dart) has a syntax-error in the first line: `@HtmlImport('element_name.html');` should be `@HtmlImport('element_name.html')`, at least according to the dartlang-extension in atom and the dart2js-compiler (version 1.12.2)

**Comment by jakemac53** [comment]
thanks
