### ISSUE TITLE
Newbie in Dart-polymer

### ISSUE THREAD

**Issue by Pelinor** [dart-lang/polymer-dart#646]
I've bought web storm and I've built the template dart with polymer and compiled. Then, I've deployed it into my web. (matemáticas-interactivas.com) And it works only ok in Chrome , Opera and of course in Chromium. But it doesn't work in IE and firefox. So, I'm wondering if I must use polymer..¿Is it an old issue?¿Is there any shortcut to avoid it?

**Comment by zoechi** [comment]
The issues on GitHub is primarily for bugs and feature requests. Can you please ask on StackOverflow.com or https://groups.google.com/a/dartlang.org/forum/?nomobile=true#!forum/web

IE and Firefox don't support shadow DOM yet, some styling things need some manual additions to make it work in browsers without native shadow DOM support. 
https://www.polymer-project.org/0.5/articles/styling-elements.html might provide some useful information (search for polyfill)
