### ISSUE TITLE
`DomRepeatModel` not returning the item

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/polymer-dart#654]
`new DomRepeatModel.fromEvent(e).item` always returns `null`.

Shouldn't `item` getter be defined as `get item => jsElement["def"]` ?

**Comment by jakemac53** [comment]
Not sure where 'def' is coming from but this does bring up a good point. If you override the items name in the template (using an `as` attribute) then this `item` getter won't work. There are a few options here:

1. Support the generic `[]` and `[]=`operators, and delete the `item` getter.
2. Support the generic `[]` and `[]=`operators, and leave the `item` getter in place (but it will only work if you don't have an `as` attribute)
3. Make the `item` getter respect the `as` attribute so it always returns the model, and leave everything else as is.
4. Support the generic `[]` and `[]=`operators, and make the `item` getter respect the `as` attribute so it always returns the model.

**Comment by dam0vm3nt** [comment]
My fault, it should be ```jsElement[jsElement["dataHost"]["as]"]]```. And of course it is returning null only when it one uses `as` attribute.

**Comment by dam0vm3nt** [comment]
That means option 3, right ?

**Comment by jakemac53** [comment]
My first instinct is #3 as well but I am a bit afraid it might lead to confusion. For instance in your template you will still be referring to the item by the name you gave for the `as` attribute, but then in your code it would always be `item`. For that reason option #1 might be better, although it is a breaking change.

That leads me to maybe #4 but adding @deprecated to the `item` getter?

**Comment by dam0vm3nt** [comment]
yeah, that seams the better choice, I agree.

**Comment by jakemac53** [comment]
fwiw,  you can also use the `get` method today with whatever name you used for `as`

**Comment by dam0vm3nt** [comment]
ok, thanks for the advice.
