### ISSUE TITLE
removeAt(path, index) TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#660]
I'm getting the following error when removing an item from a list.  The weird thing is it's notifying and the item is being removed from the UI. 
```
 var model = new DomRepeatModel.fromEvent(e);
removeAt('info.users',model.index);
```

Error:
```
Uncaught Unhandled exception:
TypeError: Cannot read property 'indexOf' of undefined
#0      JsObject.callMethod (dart:js:1075)
#1      HtmlElement&PolymerMixin&PolymerBase.removeAt (package:polymer_interop/src/polymer_base.dart:380:36)
```

**Comment by jakemac53** [comment]
This sounds like `info.users` is undefined possibly? Would it be possible for you to supply a full repro?

**Comment by terrywarwar** [comment]
```info``` is set from an iron-ajax last-response.  Will create a full repro shortly.

**Comment by terrywarwar** [comment]
I haven't able to reproduce in another app.

**Comment by jakemac53** [comment]
closing for now since I can't really take any action without a repro, please reopen if you are able to figure out more information.
