### ISSUE TITLE
null object when using $ selector of node inside dom-if

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#667]
$['id1'] returns null when inside dom-if template.  Works fine when it's outside the dom-if.
```
<template is="dom-if" if="{{!isLogin}}">
   <div id="id1"></div>
</template>
```

**Comment by zoechi** [comment]
That's "as designed". If you wrap your code with `asnyc(...)` to give Polymer time to stamp the template, it will work.

**Comment by terrywarwar** [comment]
Tried ```async(()=>($['md'] as PaperDrawerPanel).togglePanel());``` and still getting a null object.

**Comment by zoechi** [comment]
Also when `isLogin` is false?

**Comment by terrywarwar** [comment]
It' set on ready() ```set("isLogin", false);```

**Comment by jakemac53** [comment]
I am pretty sure this is working as intended. The `$` map is only going to contain things that exist on initial render. You could try setting `isLogin` to false in its initializer but I am not sure if that would work either. You should be able to use `$$('md')` instead which does an actual query for the element.
