### ISSUE TITLE
support for indexed iterable

### ISSUE THREAD

**Issue by ovangle** [dart-lang/polymer-dart#68]
Do polymer.dart expressions have support for [indexed iterables](https://www.polymer-project.org/0.5/docs/polymer/binding-types.html)? 

When I try to create one:

    <template repeat="{{item, index in items}}">
       {{index}}: <stuff-with-item item="{{item}}"></stuff-with-item>
    </template>

I get the error `"MyPolymerElement has no setter 'item'"`.

**Comment by sigmundch** [comment]
Yes, but through the `enumerate` filter:

```html
<template repeat="{{item in items | enumerate}}">
  {{item.index}}: .... {{item.value}}
```
