### ISSUE TITLE
Wrong documentation for read-only properties

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/polymer-dart#685]
In [wiki/properties#read-onlyproperties](https://github.com/dart-lang/polymer-dart/wiki/properties#read-only-properties), the sample code is not correct. `@Property(notify: true)` must be used instead of `@property`.
```` dart
@PolymerRegister('my-element')
class MyElement extends PolymerElement {
  MyElement.created() : super.created();

  @property
 // Should be @Property(notify: true)
  String get myValue => _myValue;
  String _myValue;

  @reflectable
  someEventHandler() {
    _myValue = 'hello!';
    notifyPath('myValue', _myValue);
  }
}
````

**Comment by jakemac53** [comment]
Just `@property` should be correct. All that the `notify: true` option does is opt into two way binding (upwards, by firing my-value-changed events), which is a separate thing.
