### ISSUE TITLE
Template repeat does not render items when placed inside of table

### ISSUE THREAD

**Issue by thatbrothacodes** [dart-lang/polymer-dart#686]
I am trying to repeat rows within a table. Whenever I attempt to use the repeat feature. It does not render the results. I have used other methods of repeating items, but for some reason table rows are not rendering.
`<table>
                <template is="dom-repeat" items="{{items}}" as="team">
                    <tr><td>{{team}}</td></tr>
                </template>
</table>`

**Comment by jakemac53** [comment]
This is a known issue with tables and select elements, see https://github.com/dart-lang/polymer-dart/issues/623, and https://github.com/Polymer/polymer/issues/1735

**Comment by joo** [comment]
how to solve this issue?

**Comment by jakemac53** [comment]
The workaround is to just use `div`s or other normal elements and style them as `display: table`, `display: table-row`, `display: table-cell`, etc

**Comment by lymp** [comment]
If it's a show stopper, just have the table element in html template, and add rows and cells dynamically. Works fine for me.

**Comment by joo** [comment]
# Huge setback!? more ugly than version 0.5.

**Comment by joo** [comment]
Select elements's option, how to simulate?
display: select, display: select-option, etc?

**Comment by jakemac53** [comment]
Please see the issue linked above, https://github.com/Polymer/polymer/issues/1735
