### ISSUE TITLE
Filter not working and no error

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#687]
I've got a filter set as below and it's not working.  Is there anything else I need to do or import.
`<template is="dom-repeat" items="{{data}}"
          filter="filterItems" observe="feederCode">`

`@reflectable
  bool filterItems(item, [_, __])=> item.feederCode == "XT12";`

**Comment by dam0vm3nt** [comment]
try casting the item to dart with  `convertToDart(item)`.

**Comment by terrywarwar** [comment]
just tried it, no difference.
`@reflectable
  bool filterItems(item,[_, __])=> convertToDart(item).feederCode == "XT12";`

**Comment by jakemac53** [comment]
The tests for this functionality are passing, so there must be something else going on. Can you post a more complete repro?

**Comment by terrywarwar** [comment]
will try in reproduce in a smaller app.  btw, can I pass a property into the filter like `filter="filterItems(item, text)"` with text being `@property String text`?

**Comment by jakemac53** [comment]
It looks like you can, but need to wrap it in `{{}}` if you do that, https://www.polymer-project.org/1.0/docs/devguide/templates.html#dynamic-sort-and-filter-changes

**Comment by terrywarwar** [comment]
thanks I'll try it out, what would be the equivalent function in dart, do we pass the `item` in`@reflectable bool filterItems(item,text)`

**Comment by terrywarwar** [comment]
Tried the same example with a closure 
` @reflectable
  computeFilter(t) {
    return (Employee employee) => employee.last == t;
  }`

<paper-input label="Type something..." value="{{text}}"></paper-input>` 
<template is="dom-repeat" items="{{employees}}" as="employee" filter="{{computeFilter(text)}}">`

and get this error
`Uncaught Unhandled exception:
NoSuchMethodError: method not found: 'last'
Receiver: Instance of 'JsObjectImpl'
Arguments: []
#0      JsObject.noSuchMethod.throwError (dart:js:1104)
#1      JsObject.noSuchMethod (dart:js:1114)
#2      MainApp.computeFilter.<anonymous closure> (package:dart_polymer_test/main_app.dart:39:44)
  Polymer.Async._atEndOfMicrotask	
  window.MutationObserver.observe.characterData`

Employee
`class Employee extends JsProxy {
  @reflectable
  String first;

  @reflectable
  String last;

  Employee(this.first, this.last);
}`

**Comment by terrywarwar** [comment]
`convertToDart(employee);` resolved that error.

**Comment by jakemac53** [comment]
Ah interesting, but that makes sense. I can think on how the framework might handle this automatically, but its not a trivial use case.

**Comment by terrywarwar** [comment]
`filter` works in small app.  You're right something else is going on in larger app.  Thanks.
