### ISSUE TITLE
Question: can one use dartlang/build with polymer? 

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#688]
Can one use https://github.com/dart-lang/build with polymer?

**Comment by zoechi** [comment]
I guess https://groups.google.com/a/dartlang.org/forum/#!forum/misc would be a better place for such questions.

**Comment by jakemac53** [comment]
Not today, both the web_components and reflectable transformers overwrite files currently, which is not allowed in `build`. If they are tweaked to not do that then yes it could be possible.
