### ISSUE TITLE
iPhones updated to ios10 show blank screen on Dart Polymer website

### ISSUE THREAD

**Issue by svetonius** [dart-lang/polymer-dart#714]
**Description**
iPhones updated to ios10 showing blank screen on Dart Polymer website -->

**Steps to Reproduce**
A user puts our website into his iPhone which has been updated to ios10.   Our website is written in Dart using Polymer and Web Components 

**Expected Results**
The website should load as it does on other systems, including ios9.

**Actual Results**
A blank screen appears.

We had this same problem with ios8 and ios9  on the website, with a blank screen appearing, but solved it by updating the versions for Polymer and Web Components.  

The only thing I can find about solving the ios10 issue is a recommendation to change into Web Components Light, which doesn’t seem to exist for Dart.

**Comment by AndrewLugg** [comment]
The issue occurs with Web Components, we ran into the same issue, and we found someone has come up with a solution.

[https://github.com/geppy/polymer0.5-patches-for-ios10](url)

**Comment by svetonius** [comment]
This worked!  By updating the code with this solution now the website works perfectly on ios10 phones!
