### ISSUE TITLE
Package waterfall doesn't run dartium - what platform should unit tests run on?

### ISSUE THREAD

**Issue by whesse** [dart-lang/polymer-dart#722]
There was an edit to .test_config that left only "dartium" as a test platform.  Due to problems making it work, dartium is not supported on that waterfall.  Is there another platform the unit tests could run on, and should pass on?  Otherwise, we could remove the package from the waterfall.  Let me know what you want to do.

**Comment by jakemac53** [comment]
I think it is fine to remove the package from the waterfall
