### ISSUE TITLE
Code generation issues with reflectable 1.0.1

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/polymer-dart#723]
### Description

Building a (large) polymer.dart app after upgrading to reflectable 1.0.1 causes an incorrectly generated HTML file in release mode.  Certain components (`dom-module` HTML files) are not included in the generated HTML file.

#### Steps to Reproduce

1. upgrade a project to reflectable 1.0.1
2. build in release mode
3. observe `dom-module` definitions are missing

#### Expected Results
`dom-module` definitions (i.e. paper-input) are included.

**Comment by dam0vm3nt** [comment]
Hi, probably this is the same of https://github.com/dart-lang/web-components/issues/54 .
There's a fix for `initialize` package pending to be merged

**Comment by johnpryan** [comment]
That looks like it is the issue I am seeing.  I will try running with that patch and post the results.

**Comment by johnpryan** [comment]
I can confirm this is the same issue as  dart-lang/web-components#54.  Using https://github.com/dam0vm3nt/initialize/commit/a0388461274df89b9fffd6bfe781c95132704b64 fixes this issue for me.
