### ISSUE TITLE
Polymer 1.0.0-rc.19 stopped working for me

### ISSUE THREAD

**Issue by enyo** [dart-lang/polymer-dart#724]
I am sorry because my issue is a bit hard to describe, but since I upgraded to `1.0.0-rc.19` I get a very strange behaviour, and I wondered if anybody else encountered the same problems.

**Some** of my stylings in my polymer elements stopped working. I get the error message `Could not find style data in module named common-elements` although there is style data in there:

```html
<dom-module id="common-elements">
  <template>
    <style>
      [hidden] {
        display: none !important;
      }
      ...
```

The content of my polymer elements isn't generated anymore. `$` and `$$` helper functions stopped working because of the same issue.

When I make *any* change to one of the affected files, it starts working again with `pub serve`. `pub build` always fails though.

I'm sorry for the vague description, but I'm very grateful to any pointers I could get to fix this.

**Comment by enyo** [comment]
Btw, I create many of those polymer elements with `new Element.tag('my-polymer-tag');`. Maybe that is causing the problem?

**Comment by dam0vm3nt** [comment]
Most probably is the issue with `initialize` package that's still waiting for a merge (https://github.com/dart-lang/initialize/pull/53).

**Comment by enyo** [comment]
@dam0vm3nt You saved my day! Thanks

**Comment by dam0vm3nt** [comment]
you're welcome!
