### ISSUE TITLE
Polyway to Test Components - Using polymer 0.16.X and test 0.12.x?

### ISSUE THREAD

**Issue by rayk** [dart-lang/polymer-dart#73]
Hia

Have following along with the changes and [discussion] (https://github.com/dart-lang/test/issues/91)  in test packages to support polymer.

I get the `<link rel="x-dart-test" href="unit_name_test.dart">` and understand that changes in polymer.init.dart.

But I really need some help.

My previous approach was to include the unit test in for polymer transformation. In the test itself I would init polymer and `onReady', create the with `new Element` with a nullSanitizer and then `append(_element)` this all worked well with async/await..  Then I could query and find the element, check it's shadow dom etc.

With the changes to test, I am really very unclear what is the best way to structure these unit test.

So could you help with maybe an example of our new poly'way'. I can see that you have got it working from 0.16.2 . But it just not coming together for me...fog is not lifting. Any help would be appreciated...  

In my ideal world I could:
- Not have to register the polymer test in polymer section of the pubspec.yaml.
- I could create a file in my test directory call `foo_bar_test.dart`, hopefully avoid having a custom HTML unless there was JS script dependences I needed to access.
- In the unit test `foo_bar_test.dart` I would just do something like:

```dart
import 'dart:html';
import 'package:test/test.dart';
export 'package:polymer/init.dart'

main(){

Element _testEl = createElement(<my-foo id="good_foo"></my-foo>);

test('foo should do a little dance, well at least appear on the page.',() async{
    document.body.append(_testEl);
    Element testSubject = await document.querySelector('#good_foo');
    expect( testSubject.shadowRoot, isNotNull);
});

}
```

That again is ideal world... and the above would just run along side all other test when I `pub run test -p content-shell`. Stepping back to reality an annotation would be fine... ```@polyTest``` have using ```@initMethod``` annotation  above ```main(){``` would not kill anyone..

I am just not sure of the way to proceed... I know I don't want to have anything in my setup that needs to ``await`` the zone to showup...

So a gist with a example that  we will call the poly way would really help me... Maybe that will lift my fog of war on this problem..

Thanks in advance.

**Comment by zoechi** [comment]
I  guess you need a custom html file because otherwise there is no way to register an entry point in pubspec.yaml which is necessary. Instead of maiin just use @whenPolymerReady annotation and probably a different name than main (like init)

**Comment by jakemac53** [comment]
Yes, @zoechi is correct here. You need an html file because the polymer transformer starts from html not dart code, and you should use an @whenPolymerReady annotated method to define your tests.

If you need something more custom you can write a custom main like before, but you need to return a future which does not complete until all your `test` methods have been called.

**Comment by rayk** [comment]
@zoechi & @jakemac53 .. Thanks for the advice... it is probably just must be me not getting it...

I put it all down on a [Gist](https://gist.github.com/rayk/a415195ba9b5347f6c6a). I hope you have a few moments to look at it and let me know where I am off track it would be great... I just can get it working.

I have tried to init poly from the HTML side using ``<script type="application/dart">export 'package:polymer/init.dart';</script>``  but the two script tag thing throws the Script Compacting error.

Clearly if I get rid of 
```html
<link rel="x-dart-test" href="poly_foo_test.dart"> 
<script src="packages/test/dart.js"></script> 
```

All is good with the polymer side but not the test side, test fails to load the test file. I have also combed all the doco out their on the [Polymer Site](https://www.dartlang.org/polymer/) and and everything about test. Without luck, so I am sure it is something really simple and not worth writing about... 

Thanks again guys...

**Comment by zoechi** [comment]
Looks fine except the test transformer is missing at the end of your pubspec.yaml (see test readme, I am just on my phone)

**Comment by jakemac53** [comment]
https://gist.github.com/jakemac53/b42e8e46d83c9e6474fc is a working example

**Comment by rayk** [comment]
Thanks guys.. it was that one transformer line...
