### ISSUE TITLE
Please support absolute paths in HTML imports

### ISSUE THREAD

**Issue by felixc** [dart-lang/polymer-dart#74]
Currently https://www.dartlang.org/polymer/reference/error-messages/#code_transformers_1 indicates that absolute paths in imports are not allowed. This poses some difficulty for us, as we have a single-page application that may be accessed from URLs including multiple levels (for example, not just `/` but also `/users/felixc/settings/security` or the like). These require us to reference certain components by absolute path.

Our current workaround involves the server redirecting these requests to `/#<original-path-here>`, which the web application then interprets and rewrites *back* to the original path without performing a new page load (e.g. a request to `/foo/bar/` is redirected by the server to `/#foo/bar`, which the client rewrites to `/foo/bar` once loaded). Needless to say, this is sub-optimal!

I'm sure we're not the only ones with this problem, so suggestions for a cleaner workaround would also be very welcome.

**Comment by jakemac53** [comment]
Is there any reason that package paths won't work for you? It doesn't mention them in that error message but both relative and package paths are allowed.

**Comment by felixc** [comment]
Sorry, can you elaborate on what's meant by "package paths"? Do you mean Dart code-style imports like `import 'package:polymer/polymer.dart';`? I was not aware those were supported in HTML `<link rel="import">` tags, if that's the case.

I'm looking at https://www.dartlang.org/polymer/app-directories.html#into-a-non-dart-file-under-lib in particular, which says "Non-Dart files under lib must walk up to the top of the package plus one", and gives the example `<link rel="import" href="../../packages/b/b.html">`. Do you mean that could be written as `<link rel="import" href="package:b/b.html">`?

Trying something like that gets me a linter warning:

```
line 2, column 1 of lib/app.html: absolute paths not allowed: "package:paper_elements/paper_icon_button.html". See http://goo.gl/5HPeuP#code_transformers_1 for details.
<link rel="import" href="package:paper_elements/paper_icon_button.html">
```

**Comment by sigmundch** [comment]
Where do you use the absolute path? in an HTML import? or in some other src url (an image or something else)?

HTML imports need to be resolved at the time we are compiling the application since we are vulcanizing all HTML files into a single file (all those HTML imports will be gone on a deployed app).

As for importing to files in other packages. You are correct,  HTML imports can't use `package:` URLs because the browser doesn't understand the `package:` scheme. The mechanism to use them is what you found: use a relative path with the right number of steps to walk up to the packages folder (`../../../../packages/b/b.html`).

**Comment by jakemac53** [comment]
Alternatively, you can use `package:` inside of @HtmlImport annotations, which is one of their advantages over normal html imports.

**Comment by felixc** [comment]
Right, yes, in an HTML import. And yeah, what we're seeing is that they have to use a relative path. That's why I opened the feature request to support other ways of referencing them.

I suspect I'm missing something here, since I don't think we can be the only ones with this problem. What it comes down to is this: We have a single-page application, but we want users to be able to load it from URLs other than the root. So, for example, when the user navigates to `/foo/bar/baz`, the server should actually return the same file as if they navigated to `/`. Then it's up to the smart web application to check the URL and set its internal state appropriately and render the specific page that was requested. This fails because the URLs are all relative, so the path relative to `/` is not the same as the path relative to `/foo/bar/baz`. Absolute imports would solve this.

Is there a better way? Are we kludging something that should be simple?

**Comment by jakemac53** [comment]
I haven't tried using it myself, but maybe the html `base` tag would do what you need?

**Comment by jakemac53** [comment]
Some other general questions/recommendations if the `base` tag isn't an option or doesn't work for you:

Do you have relative imports to files under your web directory? If so you should move these imported files to the lib directory and access them via packages paths. From your entry points your html imports should look something like `packages/my_package/my_import.html`, (or use `@HtmlImport('package:my_package/my_import.html')` from one of your dart files).

Does your server serve the packages directory appropriately? For instance, `/foo/bar/baz/packages` should be serving the `/packages` directory, not the `/` directory.

**Comment by felixc** [comment]
The first hurdle, even with `<base>`, is that the recommended `<script src="packages/browser/dart.js"></script>` inserts the links `<script src="packages/web_components/webcomponents.min.js"></script><script src="packages/web_components/dart_support.js">` at the very top of the `<head>` (i.e. before `<base>`, no matter how early you declare it), and hence the value isn't used, and they're fetched via relative paths.

In re: the specific recommentations:
* The only file under `web/` is the `index.html` entry-point, everything else is under `lib/`.
* Yes, the server handles `/packages/` differently and serves those files normally.
* I'll give it a try with changing everything over to `@HtmlImport`, though it would be nicer to keep HTML imports with the HTML.

**Comment by jakemac53** [comment]
With regards to the `<base>` tag, can you try adding the `<script src="packages/web_components/webcomponents.min.js"></script><script src="packages/web_components/dart_support.js">` manually after the `<base>` tag? You will get a warning but can safely ignore it. If that works for you I can work on adding a fix so that they will always get injected below a <base> tag, if one exists.

@HtmlImport is going to be the same as just adding a normal html import in your entry point to `packages/*` (in fact all it does is dynamically inject that import for you, replacing `package:` with `packages/`).

Just to confirm, you said you handle `/packages/` differently, but do you also handle `**/packages` differently? This seems to me like it is most likely the reason you are experiencing issues.

**Comment by felixc** [comment]
OK! I can confirm:

* This wasn't a problem with relative/absolute imports in HTML `<link>`s after all; sorry!
* Using `<base>` fixes everything except the scripts injected by `browser/dart.js`.
* Handling those specially on the server-side (i.e. handling `**/packages`) works.
* Manually adding them *after* `<base>` (and removing `browser/dart.js`) removes the requirement to handle `**/packages` server-side, so it would be a nice enhancement if that were handled automatically.

Thank you for all the help and for sorting out my confusion here!

**Comment by jakemac53** [comment]
Great! Closing this bug now in favor or the new issue that I opened relating to base tag support.
