### ISSUE TITLE
Upgrade plans to Polymer 1.0

### ISSUE THREAD

**Issue by ronlobo** [dart-lang/polymer-dart#80]
Hey there,

What are the plans on upgrading to Polymer 1.0 which was released recently?
Any contribution guides out there?

Best
Ron

**Comment by zoechi** [comment]
https://groups.google.com/a/dartlang.org/forum/#!topic/web/dn-KEwwgeU8

**Comment by ronlobo** [comment]
Thanks :+1:

**Comment by zoechi** [comment]
some updates https://groups.google.com/a/dartlang.org/forum/?nomobile=true#!topic/web/lKLgsxC2pdw

**Comment by DisDis** [comment]
Any news?
Group topic is very old.

**Comment by PSG-Luna** [comment]
I'd also like an update on this, been waiting for it

**Comment by AndreyChernykh** [comment]
Is there some kind of milestone or target date? We are very looking forward for that update. Thanks.

**Comment by jakemac53** [comment]
The current target date is sometime in Q3. This should also include the
various elements <https://elements.polymer-project.org/>.

- Jake

**Comment by AndreyChernykh** [comment]
Thanks, Jake. 

We are so worried about future of PolymerDart, to be honest, because there is no public milestones and so on. Sometimes this projects seems abandoned. And to us it became very risky to use such a project with unclear future in production level. Hope your team also understand that. 

Regards.

**Comment by lymp** [comment]
Advice please!
I have a Dart+Polymer 0.16.0 web-app project, 95% ready to release. I've just spent a few hours with polymer 0.16+3. Not had any *immediate* success getting my app to run.  Anyway, my question is - should I continue with this move now, or should I stick with Pol 0.16 ?  Better now, better wait? Will the pain come later anyway, or will it be more straightforward when 0.17 (1.0) is released? Release my app with 0.16, or delay (which wouldn't be a big deal really)? 
Thanks
Cheers
Steve

**Comment by jakemac53** [comment]
@lymp what specific issues are you running into with 0.16.3? There shouldn't be any breaking changes from 0.16.0, so if there are then can you file a bug with the errors you are seeing?

With respect to upgrading, if you are already almost ready to deploy with 0.16 then I would go ahead and do that. Once the next version is stable you can migrate. The only issue I can think of that you might run into is if you are using the `/deep/` or `::shadow` selectors, as they are being deprecated in chrome.

**Comment by lymp** [comment]
Thanks for the rapid reply.  I have restarted the migration from a working app with 0.16, simply by changing the yaml to 
<b>
polymer: '^0.16.3+3'
</b>

That's the only change I've made (I'm guessing there should be more to it I've played.) Anyway, the DartEditor output when I run is:
<b>
Exception: Uncaught Error: Class '_Future' has no instance method 'run'.

NoSuchMethodError: method not found: 'run'
Receiver: Instance of '_Future'
Arguments: [Closure: () => dynamic]
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      startPolymer (http://localhost:8080/rm408.dart:56:17)
#3      main.<main_async_body> (http://localhost:8080/rm408.dart:53:3) 
</b>

and rm408.dart line 56 is initPolymer in this function:

<b>
void startPolymer() {
  initPolymer().run(() {
    Polymer.onReady.then((_) {
      start();
    });
  });
}
</b>
cheers
Steve

**Comment by zoechi** [comment]
It's now easier to initialize Polymer with a custom main method  http://stackoverflow.com/a/20982658/217408

**Comment by jakemac53** [comment]
`initPolymer` now returns a Future<Zone> - this should be broken in a 0.16.0 app as well though? See changelog [here](https://github.com/dart-lang/polymer-dart/blob/master/CHANGELOG.md#0160) for examples.

**Comment by lymp** [comment]
Hi,
I've made this change from:

    Future main() async {
      await (f_lawnOpenAllRotaNames());
      startPolymer();
    }
    
     void startPolymer() {
       initPolymer().run(() {
        Polymer.onReady.then((_) {
         start();
        });
     });
    }

to:

      @whenPolymerReady
        void onReady() {
       // Custom setup code here.
       //  f_lawnOpenAllRotaNames();
       start();  
      }
 

and now get the following:
<b>
Failed to load resource: net::ERR_CACHE_MISS
  https://ssl.gstatic.com/chrome/components/doodle-notifier-02.html
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/packages/lib/css/sasstyle.css
Observatory listening at http://127.0.0.1:57462/
Breaking on exception: No top-level method 'i65.main' declared.

Exception: No top-level method 'i65.main' declared.

NoSuchMethodError: method not found: 'i65.main'
Receiver: top-level
Arguments: [...] (http://localhost:8080/rm408.bootstrap.dart:70)
</b>
I've no idea why it suddenly can't see the css.

cheers
Steve

**Comment by jakemac53** [comment]
Did  you also add `export 'package:polymer/init.dart';`?

**Comment by lymp** [comment]
No. In my HTML I have:
</b>
  <script type="application/dart">export 'rm408.dart';</script>
</b>

I changed this a few months ago from the "standard" approach (detailed somewhere on StackOverflow - can't recall where). But it's been working OK. (I'm no expert in this, so I've probably screwed up somewhere).
Thanks
S

**Comment by lymp** [comment]
Oh missed it:
script type="application/dart">export 'rm408.dart';{/script

**Comment by jakemac53** [comment]
Can you try adding `export 'package:polymer/init.dart';` to the file that
 used to have a main method? Or add a main that looks like this: `main() =>
initPolymer();`

**Comment by lymp** [comment]
Hi,
Thanks! It's beginning to work. I included the export. I need to check a few things - like finding out why the css file can't be found, and starting lawndart. But a major step forward. Thank you very much. Much appreciated.
Cheers
Steve
